# Generated by Django 4.2.1 on 2023-05-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('administrar_carreras', models.BooleanField(default=True)),
                ('administrar_cursos', models.BooleanField(default=True)),
                ('administrar_estudiantes', models.BooleanField(default=True)),
                ('administrar_docentes', models.BooleanField(default=True)),
                ('administrar_usuarios', models.BooleanField(default=True)),
                ('validar_cargas_academicas', models.BooleanField(default=True)),
                ('administrar_roles_y_permisos', models.BooleanField(default=True)),
                ('administracion_de_edificios_y_salones', models.BooleanField(default=True)),
            ],
        ),
    ]
