# Generated by Django 4.2.1 on 2023-05-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
