# Generated by Django 4.2.1 on 2023-05-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_usuarioautenticable_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioautenticable',
            name='apellido',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuarioautenticable',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usuarioautenticable',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarioautenticable',
            name='is_organisor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuarioautenticable',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuarioautenticable',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
