# Generated by Django 4.1.9 on 2023-05-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_usuarioautenticable_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
