# Generated by Django 4.2.1 on 2023-05-05 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('inicio', models.IntegerField(default=2023)),
                ('creacion', models.DateField()),
                ('proceso', models.CharField(max_length=250)),
                ('ciclos', models.IntegerField(default=2)),
                ('examen', models.IntegerField(default=100)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pensum.carrera')),
            ],
        ),
    ]
