# Generated by Django 4.2.1 on 2023-05-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensum', '0002_pensum'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensum',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
