# Generated by Django 4.2.1 on 2023-05-05 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensum', '0003_pensum_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=25)),
                ('pensum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pensum.pensum')),
            ],
        ),
        migrations.CreateModel(
            name='CursoPensum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditos', models.IntegerField(default=4)),
                ('obligatorio', models.BooleanField(default=True)),
                ('creditos_prerrequisito', models.IntegerField(default=0)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pensum.ciclo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_curso', to='pensum.curso')),
                ('curso_prerrequisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_prerrequisito', to='pensum.curso')),
            ],
        ),
    ]
