# Generated by Django 4.1.9 on 2023-05-05 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('salones', models.IntegerField(default=0)),
                ('niveles', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salon_clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField(default=0)),
                ('habilitado', models.BooleanField(default=True)),
                ('edificio', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='edificios.edificio')),
                ('salon_clasificacion', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='edificios.salon_clasificacion')),
            ],
        ),
    ]
