# Generated by Django 4.2 on 2023-05-05 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0002_salon_clasificacion_salon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salon',
            old_name='Salon_clasificacion',
            new_name='salon_clasificacion',
        ),
    ]
