# Generated by Django 4.2 on 2023-05-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0003_rename_salon_clasificacion_salon_salon_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='fecha_creacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='edificio',
            name='niveles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edificio',
            name='salones',
            field=models.IntegerField(default=0),
        ),
    ]
